version: '3'
services:
  store:
    build: ./store
    ports:
      - 8080:8080
    links:
      - db
      - auth
  auth:
    build: ./auth
    ports:
      - 8081:8081
    links:
      - db
      - rabbitmq
    depends_on:
      - rabbitmq
  sender:
    build: ./sender
    ports:
      - 8082:8082
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
  db:
    image: "redis:alpine"
    ports:
      - 6379:6379
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672