version: '3'

services:
  store:
    build: ./store
    ports:
      - 8080:8080
    links:
      - db
      - auth
  auth:
    build: ./auth
    ports:
      - 8081:8081
    links:
      - db
      - rabbitmq
  sender:
    build: ./sender
    links:
      - rabbitmq
  db:
    image: "redis:alpine"
    ports:
      - 6379:6379
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - 5672:5672
      - 15672:15672
  reader:
    build: ./reader
    ports:
      - 8083:8083
    links:
      - rabbitmq
  writer:
    build: ./writer
    links:
      - rabbitmq
