version: '3'
services:
  web:
    build: ./store
    ports:
      - 8080:8080
    links:
      - db
  auth:
    build: ./auth
    ports:
      - 8081:8081
    links:
      - db
  db:
    image: "redis:alpine"
    ports:
      - 6379:6379